### ISSUE TITLE
Error running "npm install" or "npm run build"

### ISSUE THREAD

**Issue by github-vipera** [crcn/aerial#38]
Hi
i'm very interested and intrigued by this project and i tried to run the playground example.
I downloaded a copy of this repository but when i run the "npm install" shell command but it fails with the same error at build stage. Here the latest console log lines:

[20:09:18] Starting 'build'...
[20:09:18] npm run build ./packages/aerial-browser-sandbox
[20:09:19] > aerial-browser-sandbox@0.0.3 build /Users/marcobonati/Develop/temp/aerial-master/packages/aerial-browser-sandbox
> rm -rf lib; for FILE in `find ./src -name *.peg`; do OUT_FILE=`echo $FILE | sed 's/src/lib/' | sed 's/.peg/.peg.js/';`; mkdir -p `dirname $OUT_FILE`; ./node_modules/.bin/pegjs -o $OUT_FILE $FILE; done; for FILE in `find ./src -name *.d.ts`; do OUT_FILE=`echo $FILE | sed 's/src/lib/'`; mkdir -p `dirname $OUT_FILE`; cp $FILE $OUT_FILE; done; tsc
[20:09:26] src/constants/index.ts(2,8): error TS2322: Type '"PX"' is not assignable to type 'CSSMeasurementTypes'.
[20:09:26] src/constants/index.ts(3,10): error TS2322: Type '"%"' is not assignable to type 'CSSMeasurementTypes'.
[20:09:26] src/constants/index.ts(4,8): error TS2322: Type '"vw"' is not assignable to type 'CSSMeasurementTypes'.
src/constants/index.ts(5,8): error TS2322: Type '"vh"' is not assignable to type 'CSSMeasurementTypes'.
src/constants/index.ts(6,8): error TS2322: Type '"cm"' is not assignable to type 'CSSMeasurementTypes'.
[20:09:26] src/constants/index.ts(7,8): error TS2322: Type '"em"' is not assignable to type 'CSSMeasurementTypes'.
src/constants/index.ts(8,8): error TS2322: Type '"ex"' is not assignable to type 'CSSMeasurementTypes'.
src/constants/index.ts(9,8): error TS2322: Type '"in"' is not assignable to type 'CSSMeasurementTypes'.
[20:09:26] src/constants/index.ts(10,8): error TS2322: Type '"mm"' is not assignable to type 'CSSMeasurementTypes'.
src/constants/index.ts(11,8): error TS2322: Type '"pc"' is not assignable to type 'CSSMeasurementTypes'.
[20:09:26] src/constants/index.ts(12,8): error TS2322: Type '"pt"' is not assignable to type 'CSSMeasurementTypes'.
src/constants/index.ts(13,10): error TS2322: Type '"vmin"' is not assignable to type 'CSSMeasurementTypes'.
[20:09:26] src/constants/index.ts(17,16): error TS2322: Type '"HORIZONTAL"' is not assignable to type 'Axis'.
[20:09:26] src/constants/index.ts(18,14): error TS2322: Type '"VERTICAL"' is not assignable to type 'Axis'.
src/environment/custom-element-registry.ts(3,16): error TS2420: Class 'SEnvCustomElementRegistry' incorrectly implements interface 'CustomElementRegistry'.
  Types of property 'whenDefined' are incompatible.
    Type '(name: string) => Promise<void> | Promise<{}>' is not assignable to type '(name: string) => PromiseLike<void>'.
      Type 'Promise<void> | Promise<{}>' is not assignable to type 'PromiseLike<void>'.
        Type 'Promise<{}>' is not assignable to type 'PromiseLike<void>'.
          Types of property 'then' are incompatible.
            Type '<TResult1 = {}, TResult2 = never>(onfulfilled?: (value: {}) => TResult1 | PromiseLike<TResult1>, ...' is not assignable to type '<TResult1 = void, TResult2 = never>(onfulfilled?: (value: void) => TResult1 | PromiseLike<TResult...'.
              Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                Type '(value: void) => any' is not assignable to type '(value: {}) => any'.
                  Types of parameters 'value' and 'value' are incompatible.
                    Type '{}' is not assignable to type 'void'.
src/environment/custom-element-registry.ts(39,46): error TS2322: Type 'Promise<{}>' is not assignable to type 'Promise<void>'.
  Type '{}' is not assignable to type 'void'.
[20:09:26] src/environment/nodes/element.ts(320,37): error TS2304: Cannot find name 'InsertPosition'.
src/environment/nodes/element.ts(324,31): error TS2304: Cannot find name 'InsertPosition'.
src/environment/nodes/element.ts(328,31): error TS2304: Cannot find name 'InsertPosition'.
[20:09:26] src/environment/window.ts(362,30): error TS2322: Type 'SEnvCustomElementRegistry' is not assignable to type 'CustomElementRegistry'.
  Types of property 'whenDefined' are incompatible.
    Type '(name: string) => Promise<void> | Promise<{}>' is not assignable to type '(name: string) => PromiseLike<void>'.
      Type 'Promise<void> | Promise<{}>' is not assignable to type 'PromiseLike<void>'.
        Type 'Promise<{}>' is not assignable to type 'PromiseLike<void>'.
src/utils/synthetic-element-bounds.ts(89,106): error TS2535: Enum type 'Axis' has members with initializers that are not literals.
../aerial-common2/src/log/base.ts(24,9): error TS2322: Type '"LOG"' is not assignable to type 'LogActionTypes'.
../aerial-common2/src/log/base.ts(27,85): error TS2345: Argument of type 'LogActionTypes' is not assignable to parameter of type 'string'.
[20:09:26] 
[20:09:26] npm
[20:09:26] ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm
[20:09:26] ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! aerial-browser-sandbox@0.0.3 build: `rm -rf lib; for FILE in `find ./src -name *.peg`; do OUT_FILE=`echo $FILE | sed 's/src/lib/' | sed 's/.peg/.peg.js/';`; mkdir -p `dirname $OUT_FILE`; ./node_modules/.bin/pegjs -o $OUT_FILE $FILE; done; for FILE in `find ./src -name *.d.ts`; do OUT_FILE=`echo $FILE | sed 's/src/lib/'`; mkdir -p `dirname $OUT_FILE`; cp $FILE $OUT_FILE; done; tsc`
npm ERR! Exit status 2
npm ERR!
[20:09:26] npm ERR! Failed at the aerial-browser-sandbox@0.0.3 build script 'rm -rf lib; for FILE in `find ./src -name *.peg`; do OUT_FILE=`echo $FILE | sed 's/src/lib/' | sed 's/.peg/.peg.js/';`; mkdir -p `dirname $OUT_FILE`; ./node_modules/.bin/pegjs -o $OUT_FILE $FILE; done; for FILE in `find ./src -name *.d.ts`; do OUT_FILE=`echo $FILE | sed 's/src/lib/'`; mkdir -p `dirname $OUT_FILE`; cp $FILE $OUT_FILE; done; tsc'.
npm ERR!
[20:09:26] Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aerial-browser-sandbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf lib; for FILE in `find ./src -name *.peg`; do OUT_FILE=`echo $FILE | sed 's/src/lib/' | sed 's/.peg/.peg.js/';`; mkdir -p `dirname $OUT_FILE`; ./node_modules/.bin/pegjs -o $OUT_FILE $FILE; done; for FILE in `find ./src -name *.d.ts`; do OUT_FILE=`echo $FILE | sed 's/src/lib/'`; mkdir -p `dirname $OUT_FILE`; cp $FILE $OUT_FILE; done; tsc
npm ERR! You can get information on how to open an issue for this project with:
npm
[20:09:26] ERR!     npm bugs aerial-browser-sandbox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aerial-browser-sandbox
npm ERR! There is likely additional logging output above.
[20:09:26] 
[20:09:26] npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marcobonati/Develop/temp/aerial-master/packages/aerial-browser-sandbox/npm-debug.log
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: command "npm run build" exited with an error code: 1
    at ChildProcess.proc.on (/Users/marcobonati/Develop/temp/aerial-master/gulpfile.js:46:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! aerial@1.0.0 postinstall: `gulp clean; gulp install; gulp link; gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aerial@1.0.0 postinstall script 'gulp clean; gulp install; gulp link; gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aerial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp clean; gulp install; gulp link; gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aerial
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aerial
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marcobonati/Develop/temp/aerial-master/npm-debug.log

 thanks
regards
Marco

**Comment by crcn** [comment]
Thanks for the heads up! Right now the codebase is a bit messy while I'm getting the playground to a more stable state. I went ahead and fixed them for now, so you should be able to play around with it. 

The setup process is a little more involved, so here's an instructional GIF to help you out:

![b](https://user-images.githubusercontent.com/757408/30287792-5d4b6dca-96f4-11e7-9ff8-fb739efa3ed9.gif)

Assuming that you have `VSCode` and `yarn` installed, Here are the steps to play around with the playground:

1. run `yarn install` in the main repo
2. In terminal, `cwd` into `packages/vscode-aerial-extension` and run `code .`
3. Run the VSCode debugger
4. When the debugger app loads, open the `examples/playground` directory
5. Run the `Open in Aerial view` command and wait a few seconds (~3) for it to load.
6. Wait another couple of seconds for the second window to pop up (Playground webpack bundler is running at this point)
7. Open the file `gutter/index-preview.tsx`, and either a) edit that file and save it in VSCode, or b) move the `GUTTER` text in the `Aerial view` pane around on the canvas.

Note that there are various key commands that you can execute in `Aerial view` that you can check out here: https://github.com/crcn/aerial/blob/master/examples/playground/src/front-end/state/index.ts#L347

Aerial is moving towards being a visual editor directly in your text editor (aerial will be standalone too), so the final step for this will eventually be to install the `Aerial VSCode extension` (and Atom) which will work with HTML & CSS out of the box. For additional language & tooling support for things like Webpack, TypeScript, JSX, and SASS, you'll need to to add a `visual-dev.config.js` file -- you can checkout an example here: https://github.com/crcn/aerial/blob/master/examples/playground/visual-dev.config.js.
